### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by hmm-star** [Rene-Capistran/QuizletBlurRemover#1]

**Comment by Rene-Capistran** [comment]
Thanks for letting me know. Looks like they changed some class names a while back, so I updated them.

**Comment by hmm-star** [comment]
thank you so much for your response. But the script is still not working. is there anything additional that i should do to make it work ?
regards
--hmm-star

**Comment by Rene-Capistran** [comment]
Have you added the script to tampermonkey and enabled it? also, if you wouldn't mind, a link to the set you're trying to unblur might help.

**Comment by hmm-star** [comment]
yes sir i did use tampemonkey.   below you may find the link. I am using brave browser 
https://quizlet.com/explanations/textbook-solutions/chemistry-the-molecular-nature-of-matter-and-change-7th-edition-9780073511177/chapter-1-exercises-16-16d6ec34-38a0-4d95-9b23-4d7886c13a52

**Comment by Rene-Capistran** [comment]
I see. The problem here is that these exercises are locked behind a paywall rather than just a login-wall. It would probably be illegal for me to publish a full paywall bypass, so I'm afraid I can't take this any further.

**Comment by hmm-star** [comment]
okay. I thought your script refers to blur removal which was no different from paywall bypass. I confused two things together. Actually the paywall bypass was easy as i was able to do that  but the text that appears after removing the blur appears to be obfuscated/scrambled, I was seeking help on that part.
By the way thank you for your time and efforts on this thread. You many close it now
regards
--hmm-star

**Comment by Rene-Capistran** [comment]
My blur remover is only meant to remove the blur on the login-wall, not the paywall. They are indeed different things, as one prevents the user from reading material unless they log in, and the other prevents them from reading unless they pay a subscription fee. I can tell you, however, that if you want to see the unscrambled text, try opening the link in an incognito tab and removing the blur from there.
